name: tourist_tour_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #state management
  flutter_bloc: ^8.1.3
  #code generate
#  freezed: ^2.4.5
#  freezed_annotation: ^2.4.1
  #Dependency injection
#  get_it: ^7.6.4
#  #Automatically generate code for convert to and from json
#  json_serializable: ^6.7.1
#  json_annotation: ^4.8.1
  #Networking
#  dio: ^5.4.0
#  retrofit: ^4.0.3
#  retrofit_generator: ^8.0.5
#  pretty_dio_logger: ^1.3.1
  #Localization
  intl: ^0.18.1
  easy_localization: ^3.0.3
  #for Splash screen
  flutter_native_splash: ^2.3.6
  # an svg rendering
  flutter_svg: ^2.0.9
  #adapting screen and font size
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  shared_preferences: ^2.1.1
  persistent_bottom_nav_bar: ^5.0.2
  device_preview: ^1.1.0
  hexagon: ^0.2.0
  dots_indicator: ^2.1.1
  flutter_rating_bar: ^4.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/translation/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400

          # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
