name: tourist_tour_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.7
  #state management
  flutter_bloc: ^8.1.3
  #code generate
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  #Dependency injection
  get_it: ^7.6.4
#  #Automatically generate code for convert to and from json
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  #Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.5
  pretty_dio_logger: ^1.3.1
  #Localization
  intl: ^0.18.1
  easy_localization: ^3.0.4
  # an svg rendering
  flutter_svg: ^2.0.9
  #adapting screen and font size
  flutter_screenutil: ^5.9.0
  # show message
  fluttertoast: ^8.2.4
  #some package
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  shared_preferences: ^2.1.1
  device_preview: ^1.1.0
  dropdown_button2: ^2.3.9
  flutter_rating_bar: ^4.0.0
  country_list_pick: ^1.0.1+6
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  image_picker: ^1.0.7
  video_player: ^2.8.2
  google_maps_flutter: ^2.5.1
  geolocator:
  geocoding:


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/translation/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-LightItalic.ttf
          weight: 200
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 500
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 800

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800

          # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
